mysite/urls.py
# Source Generated with Decompyle++
# File: urls.pyc (Python 2.7)

"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^passingships/', include('passingships.urls', namespace = 'passingships')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

passingships/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^profileupdate.html', views.editprofile, name='editprofile'),
    url(r'^newitinerary.html', views.newitinerary, name='newitinerary'),
    url(r'^(?P<pk>[0-9]+)/edititinerary.html', views.edititinerary, name='edititinerary'),
]

passingships/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from cities_light.abstract_models import AbstractCity, AbstractRegion, AbstractCountry
from cities_light.receivers import connect_default_signals
import cities_light
from cities_light.settings import ICity
from django.db.models.signals import post_save

PRICES = (('LO', 'Cheap'), ('ME', 'Medium'), ('HI', 'High'))
PACE = (('SL', 'Slow'), ('FA', 'Fast'))
PLANNING = (('STR', 'Strict'), ('REL', 'Relaxed'))
ACTIVITIES = (('SIT', 'Sightseeing'), ('NAT', 'Nature'), ('PAR', 'Partying & Nightlife'), ('MUS', 'Museums'), ('ART', 'Art'), ('FOO', 'Food & Dining'), ('OFF', 'Off the beaten path'), ('ACT', 'Active & Exercise'))

def set_city_fields(sender, instance, items, **kwargs):
    instance.timezone = items[ICity.timezone]

cities_light.signals.city_items_post_import.connect(set_city_fields)

class Country(AbstractCountry):
    pass

connect_default_signals(Country)

class Region(AbstractRegion):
    pass

connect_default_signals(Region)

class City(AbstractCity):
    pass
    timezone = models.CharField(max_length = 40)

connect_default_signals(City)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    age = models.IntegerField(blank = True, null = True)
    home_country = models.ForeignKey(Country, related_name = 'personcountry', blank = True, null = True)
    home_city = models.ForeignKey(City, related_name = 'personcity', blank = True, null = True)

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class Itinerary(models.Model):
    country = models.ForeignKey(Country, related_name = 'itinerarycountry', blank = True, null = True)
    city = models.ForeignKey(City, related_name = 'itinerarycity', blank = True, null = True)
    start_date = models.DateField()
    end_date = models.DateField()
    price = models.CharField(max_length = 3, choices = PRICES)
    pace = models.CharField(max_length = 2, choices = PACE)
    name = models.CharField(max_length = 100)
    description = models.TextField()
    owner = models.ForeignKey(User, related_name = 'itineraries')

passingships/forms.py
from django.contrib.auth.models import User
from .models import UserProfile, City, Itinerary
from django import forms

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('age', 'home_country', 'home_city')

class ItineraryForm(forms.ModelForm):
    class Meta:
        model = Itinerary
        fields = ('country', 'city', 'start_date', 'end_date', 'price', 'pace', 'name', 'description')

passingships/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.context_processors import csrf
from django.template.context import RequestContext
from django.contrib.auth.models import User
from .models import UserProfile, Itinerary
from .forms import UserProfileForm, ItineraryForm
from django.views.generic.detail import DetailView

def home(request):
    context = RequestContext(request, {
        'request': request,
        'user': request.user })
    return render_to_response('passingships/home.html', context_instance = context)


def editprofile(request):
    puser = UserProfile.objects.get(user = request.user)
    if request.POST:
        form = UserProfileForm(request.POST, instance = puser)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.user = request.user
            profile.save()
            return HttpResponseRedirect('/passingships/')
    form = UserProfileForm(instance = puser, initial = {
        'age': puser.age,
        'home_country': puser.home_country,
        'home_city': puser.home_city })
    print(puser.id)
    args = { }
    args.update(csrf(request))
    args['form'] = form
    return render(request, 'passingships/profileupdate.html', args)


def newitinerary(request):
    if request.POST:
        form = ItineraryForm(request.POST)
        if form.is_valid():
            itinerary = form.save(commit = False)
            itinerary.owner = request.user
            itinerary.save()
            return HttpResponseRedirect('/passingships/')
    form = ItineraryForm()
    args = { }
    args.update(csrf(request))
    args['form'] = form
    return render(request, 'passingships/newitinerary.html', args)


def edititinerary(request, pk):
    itinerary = get_object_or_404(Itinerary, pk = pk)
    if request.POST:
        form = ItineraryForm(request.POST, instance = itinerary)
        if form.is_valid():
            itinerary = form.save(commit = False)
            itinerary.owner = request.user
            itinerary.save()
            return HttpResponseRedirect(reverse('passingships:detail', args = (request.user.id,)))
    form = ItineraryForm(instance = itinerary)
    args = { }
    args.update(csrf(request))
    args['form'] = form
    return render(request, 'passingships/newitinerary.html', args)


class DetailView(DetailView):
    context_object_name = 'user'
    model = User
    template_name = 'passingships/detail.html'
    
    def get_queryset(self):
        return User.objects.prefetch_related('itineraries').all()

passingships/templates/passingships/base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}TripMate{% endblock %}</title>
 </head>
 <body>
   {% block main %}{% endblock %}
 </body>
</html>

passingships/templates/passingships/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile overview</title>
</head>
<body>
<section>
    <p><a href="{% url 'passingships:newitinerary' %}">Add a new itinerary</a></p>
    {% for itinerary in user.itineraries.all %}
    <ul>
        <li><b>Name:</b> {{ itinerary.name }}</li>
        <li><b>Description:</b> {{ itinerary.description }}</li>
        <li><b>City:</b> {{ itinerary.city }}</li>
        <li><b>Country:</b> {{ itinerary.country }}</li>
        <li><b>When:</b> {{ itinerary.start_date }} to {{ itinerary.end_date }}</li>
        <li><b>Price point:</b> {{ itinerary.get_price_display }}</li>
        <li><b>Pace:</b> {{ itinerary.get_pace_display }}</li>
        <li><a href="{% url 'passingships:edititinerary' itinerary.id %}">Edit this itinerary</a></li>
    </ul>
    {% endfor %}
</section>
<nav>
    <ul>
        <li><a href="{% url 'passingships:home' %}">Home page</a></li>
        <li><a href="{% url 'auth:logout' %}?next=/passingships/">Logout</a></li>
    </ul>
</nav>
</body>
</html>

passingships/templates/passingships/edititinerary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit itinerary</title>
</head>
<body>
<section>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
    <input type="submit" value="Save" />
    </form>
</section>
<nav>
    <ul>
        <li><a href="{% url 'passingships:home' %}">Home page</a></li>
        <li><a href="{% url 'auth:logout' %}?next=/thirdauth/">Logout</a></li>
    </ul>
</nav>
</body>
</html>

passingships/templates/passingships/home.html
{% extends 'passingships/base.html' %}

{% block main %}
 <div>
 <h1>Tripmate finder</h1>

 <p>
   <ul>
   {% if user and not user.is_anonymous %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a>Meet some people while traveling away from {{ user.userprofile.home_city.name }}!</a>
     </li>
     <li>
       <a href="{% url 'passingships:editprofile' %}">Edit profile here</a>
     </li>
     <li>
       <a href="{% url 'passingships:detail' user.id %}">View your current itineraries</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login through Google</a>
     </li>
   {% endif %}
   </ul>
 </p>
 </div>
{% endblock %}

passingships/templates/passingships/newitinerary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New ininerary</title>
</head>
<body>
<section>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
    <input type="submit" value="Add itinerary" />
</form>
</section>
<nav>
    <ul>
        <li><a href="{% url 'passingships:home' %}">Home page</a></li>
        <li><a href="{% url 'auth:logout' %}?next=/passingships/">Logout</a></li>
    </ul>
</nav>
</body>
</html>

passingships/templates/passingships/profileupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile Update</title>
</head>
<body>
<section>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
    <input type="submit" value="Save" />
</form>
</section>
<nav>
    <ul>
        <li><a href="{% url 'passingships:home' %}">Home page</a></li>
        <li><a href="{% url 'auth:logout' %}?next=/passingships/">Logout</a></li>
    </ul>
</nav>
</body>
</html>